import {useEffect,useMemo,useState} from 'react';import {Link} from 'react-router-dom';import {products as defaults} from '../data';import Header from '../components/Header';import '../admin.css';
const KEY='lunera_products', ORDER='lunera_orders';
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)&&x.length?x:defaults.map(p=>({...p,visible:true,featured:false}))}catch{return defaults.map(p=>({...p,visible:true,featured:false}))}}
export default function Admin(){const [products,setProducts]=useState(load),[orders,setOrders]=useState(()=>JSON.parse(localStorage.getItem(ORDER)||'[]')),[tab,setTab]=useState('products'),[search,setSearch]=useState(''),[editing,setEditing]=useState(null),[toast,setToast]=useState('');
useEffect(()=>localStorage.setItem(KEY,JSON.stringify(products)),[products]);
const visible=products.filter(p=>p.visible!==false).length,low=products.filter(p=>(p.stock||0)<10).length;
const filtered=useMemo(()=>products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(search.toLowerCase())),[products,search]);
const openNew=()=>setEditing({id:'',name:'',description:'',price:0,category:'Face',image:'/assets/aleo tube.jfif',rating:5,reviews:0,stock:10,visible:true,featured:false});
const save=p=>{setProducts(prev=>prev.some(x=>x.id===p.id)?prev.map(x=>x.id===p.id?p:x):[...prev,{...p,id:p.id||`product-${Date.now()}`}]);setEditing(null);setToast('Product saved ✓')};
const remove=id=>{if(confirm('Delete this product?'))setProducts(prev=>prev.filter(p=>p.id!==id))};
return <><Header admin/><main className="admin-main"><div className="admin-title"><div><p className="eyebrow">LUNÉRA / ADMIN</p><h1>Quietly<br/><em>in control.</em></h1><p>Manage products and orders for your small-batch store.</p></div><button className="admin-primary-btn" onClick={openNew}>+ New product</button></div><div className="stats-grid"><div className="stat-card"><span className="stat-label">TOTAL PRODUCTS</span><strong>{products.length}</strong></div><div className="stat-card"><span className="stat-label">VISIBLE</span><strong>{visible}</strong></div><div className="stat-card"><span className="stat-label">LOW STOCK</span><strong>{low}</strong></div><div className="stat-card"><span className="stat-label">ORDERS</span><strong>{orders.length}</strong></div></div><div className="admin-tabs"><button className={`admin-tab ${tab==='products'?'active':''}`} onClick={()=>setTab('products')}>Products</button><button className={`admin-tab ${tab==='orders'?'active':''}`} onClick={()=>setTab('orders')}>Orders</button></div>{tab==='products'?<section className="admin-panel active"><div className="panel-toolbar"><div className="admin-search"><span>⌕</span><input placeholder="Search products..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="product-admin-list">{filtered.map(p=><div className="admin-product" key={p.id}><img src={p.image} alt=""/><div><strong>{p.name}</strong><p>{p.category} · ${p.price}</p></div><span>{p.stock} in stock</span><button className="admin-icon-btn" onClick={()=>setEditing(p)}>Edit</button><button className="admin-icon-btn" onClick={()=>remove(p.id)}>Delete</button></div>)}</div></section>:<section className="admin-panel active"><div className="orders-list">{orders.length?orders.map(o=><article className="admin-order" key={o.id}><strong>Order #{String(o.id).slice(-6)}</strong><p>{o.customer?.name} · {o.customer?.email}</p><p>{o.items?.length||0} items · ${o.total} · {o.status}</p></article>):<p className="muted">No orders yet.</p>}</div></section>}</main>{editing&&<ProductModal product={editing} onSave={save} onClose={()=>setEditing(null)}/>} {toast&&<div className="toast show">{toast}</div>}</>}
function ProductModal({product,onSave,onClose}){const [p,setP]=useState(product);const set=(k,v)=>setP({...p,[k]:v});return <div className="modal-backdrop"><div className="product-modal"><button className="modal-close" onClick={onClose}>×</button><p className="eyebrow">PRODUCT</p><h2>{product.id?'Edit product':'New product'}</h2>{[['name','Name'],['description','Description'],['price','Price'],['category','Category'],['image','Image path'],['stock','Stock']].map(([k,l])=><label key={k}>{l}<input value={p[k]} onChange={e=>set(k,['price','stock'].includes(k)?Number(e.target.value):e.target.value)}/></label>)}<div className="modal-actions"><button className="admin-icon-btn" onClick={onClose}>Cancel</button><button className="admin-primary-btn" onClick={()=>onSave(p)}>Save product</button></div></div></div>}
